### ISSUE TITLE
Hosts ignored for reverse lookups

### ISSUE THREAD

**Issue by bezibaerchen** [JeDaYoshi/docker-nextdns#1]
Dear all,

I am experiencing an issue with DNS Lookups.
Background: I maintain everything in /etc/hosts as the dream machine doesn't properly answer if there is no local entry (which needs a fixed IP).

Following scenario:

docker-compose.xml

`version: "3"

services:
  nextdns:
    container_name: "nextdns-ultimate"
    image: "jedayoshi/nextdns:latest"
    restart: "unless-stopped"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      NEXTDNS_CONFIG: "xxxxxx" 
      NEXTDNS_CACHE_SIZE: "10m"
      NEXTDNS_REPORT_CLIENT_INFO: "true"
      NEXTDNS_USE_HOSTS: "true"
      NEXTDNS_FORWARDER_ROUTER: ".local=x.x.x.x"      
      NEXTDNS_FORWARDER_PTR: "168.192.in-addr.arpa=x.x.x.x" 
      NEXTDNS_LOG-QUERIES: "true"
    volumes:
      - "/etc/hosts:/etc/hosts:ro"
    hostname: nextdns_docker
`

nslookup on host running the docker image (Host-IP 192.168.1.38)

`nslookup
> 192.168.1.200
200.1.168.192.in-addr.arpa      name = debobsrv001.fuchsbau.local.

Authoritative answers can be found from:
>
`

nslookup from another host in the network:

`> server 192.168.1.38
Default Server:  [192.168.1.38]
Address:  192.168.1.38

> 192.168.1.200
Server:  [192.168.1.38]
Address:  192.168.1.38

*** [192.168.1.38] can't find 192.168.1.200: Non-existent domain
>`

For the records, hosts entry on .38:

`grep 192.168.1.200 /etc/hosts
192.168.1.200   debobsrv001.fuchsbau.local
`

Any idea why hosts-file seems to be ignored and nothing gets returned?

Thanks,

Ben

**Comment by jeda** [comment]
Hey there!
Amazes me people are using this.

It's not an issue with the script, but you're missing setting `-bogus-priv` to false.
From NextDNS help:
```
  -bogus-priv
    	Bogus private reverse lookups.
    	
    	All reverse lookups for private IP ranges (ie 192.168.x.x, etc.) are
    	answered with "no such domain" rather than being forwarded upstream.
    	The set of prefixes affected is the list given in RFC6303, for IPv4
    	and IPv6. (default true)
```

Edit your `docker-compose.yml` and include `NEXTDNS_BOGUS_PRIV: "false"` in your environment values, then it should work.

**Comment by bezibaerchen** [comment]
I'm indeed a happy user of this :-)

Thanks for your swift reply. Answer remaint Non-existent domain still. Any other idea?

**Comment by jeda** [comment]
I tried using the included `docker-compose.yml`, and it was answering the reverse lookup for the entry in the `/etc/hosts`, but not for the Split Horizon forwarder until I set `NEXTDNS_BOGUS_PRIV`. Afterwards, both worked, both from the Docker host and from another device in the same network. Also worked when querying inside the container itself.

If it's still not working for you, I'm not sure what'd be wrong.

**Comment by bezibaerchen** [comment]
I did some more testing and stumbled over something I forgot to add - sorry for this.
The client which is failing is running the NextDNS Windows app as it uses another config.
On Clients directly having the Docker instances assigned as DNS everything is working fine.

**Comment by jeda** [comment]
Yeah, I don't think that will work, since it's likely hijacking the DNS queries as Windows works differently in that matter to set other DNS servers. You might want to disable NextDNS on your Windows machine, point it to use the DNS server running on Docker, and set the Windows machine IP to use another config using a [conditional profile](https://github.com/nextdns/nextdns/wiki/Conditional-Profile).

**Comment by bezibaerchen** [comment]
Could you advise as of how this would properly translate to docker-compose?
I seem to be too supid to transport this.

I tried.

NEXTDNS_PROFILE_BUTA: "18:C0:4D:80:CD:A8=6236a7"

**Comment by jeda** [comment]
I'm going to delete that comment since you don't want to expose your profile ID nor your computer's MAC address. But you're using the MAC address instead of the IP address - you probably don't want to do that, since I don't think that's passed to the container unless you were to use `host` networking mode on Docker.

**Comment by bezibaerchen** [comment]
Thanks for deleting the comment, I forgot about the profile ID and MAC.

Below also makes the container exit:

    environment:
      NEXTDNS_CONFIG: "xxxxx"
      NEXTDNS_CACHE_SIZE: "10m"
      NEXTDNS_REPORT_CLIENT_INFO: "true"
      NEXTDNS_USE_HOSTS: "true"
      NEXTDNS_FORWARDER_ROUTER: ".local=x.x.x.x" 
      NEXTDNS_FORWARDER_PTR: "168.192.in-addr.arpa=x.x.x.x"      NEXTDNS_LOG-QUERIES: "true"
      NEXTDNS_BOGUS_PRIV: "true"
      NEXTDNS_PROFILE_BUTA: "IP.IP.IP.IP=profileID"

**Comment by bezibaerchen** [comment]
I am actually wondering about "NEXTDNS_CONFIG" vs. NEXTDNS_PROFILE" looking at your Readme....

**Comment by jeda** [comment]
I'd correct the few things:
```
  NEXTDNS_FORWARDER_ROUTER: ".local=x.x.x.x"
```
The dot is redundant. Use this:
```
  NEXTDNS_FORWARDER_ROUTER: "local=x.x.x.x"
```
Also,
```
  NEXTDNS_FORWARDER_PTR: "168.192.in-addr.arpa=x.x.x.x"      NEXTDNS_LOG-QUERIES: "true"
```
Implying this wasn't a copy-paste mistake, you want these both to be in separate lines.
```
  NEXTDNS_FORWARDER_PTR: "168.192.in-addr.arpa=x.x.x.x"
  NEXTDNS_LOG_QUERIES: "true"
```

That should work, though. In case it's not working, please paste the entire log that the container returns, after redacting sensitive details.

---

The config/profile difference is that NextDNS previously used `-config`, but this was renamed to `-profile`, so I've adjusted it in the README and in the script now. They are equivalently the same, though. You might want to pull the build I pushed a while ago, regardless, in case you haven't already.

**Comment by bezibaerchen** [comment]
I made your adjustments, also did IP/32 when assigning.
I also pulled latest image for all isntances and everything is working fine now and device is using wanted configuration.

Thanks you SO much!
