### ISSUE TITLE
Build NextDns CLI 1.41

### ISSUE THREAD

**Issue by dorseg** [JeDaYoshi/docker-nextdns#5]
Hi @JeDaYoshi, could you pleae build an image using the latest NextDNS CLI 1.41?
https://github.com/nextdns/nextdns/releases/tag/v1.41.0
Thanks

**Comment by jeda** [comment]
Ah, I didn't notice there was a new release.

Sure thing. But maybe I'll fix the automation first...

**Comment by jeda** [comment]
Sorry for the delay. I've just made a small commit for the build workflow to run.
I haven't had time yet to fix the automatic run; but hopefully, if you still need it, this will work for now.

`v1.42.0` should be available now.

**Comment by jeda** [comment]
I believe the workflow should be fixed now. Should be automatically built as originally proposed from now on.
